#
# Makefile for the drm device driver.  This driver provides support for the
# Direct Rendering Infrastructure (DRI) in XFree86 4.1.0 and higher.

iitdgi-y := iitdgi_drv.o

obj-$(CONFIG_DRM_IITDGI) += iitdgi.o
