snd-soc-iit-gla-objs := gla.o
snd-soc-iit-ssm2518-objs := adi_ssm2518.o
snd-soc-zed-adau1761-objs := zed_adau1761.o

obj-$(CONFIG_SND_SOC_IIT_GLA) += snd-soc-iit-gla.o
obj-$(CONFIG_SND_SOC_IIT_SSM2518) += snd-soc-iit-ssm2518.o
obj-$(CONFIG_SND_SOC_ZED_ADAU1761) += snd-soc-zed-adau1761.o

